{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-alpha13/runtime-1.0.0-alpha13.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha13.klib",
          "url": "runtime-js-1.0.0-alpha13.klib",
          "size": 565666,
          "sha512": "d758705a77675c1218b2d67af4a584fcfa5a406eb170577e6c86bb260beed61acccad3eac7b80cc225fdd2c282ad7d08271e47f9ce41ef78f3035147ea1f11b4",
          "sha256": "a2b4c9ffa77ccc10c768e9c8c9869750c87c0e9238dec776661367e565cde6a4",
          "sha1": "32809ef03ebc6aa35c9686b724c5ebb5091c0c6d",
          "md5": "4dfbabe5bd86025e4e349458cf68f9f7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha13.klib",
          "url": "runtime-js-1.0.0-alpha13.klib",
          "size": 565666,
          "sha512": "d758705a77675c1218b2d67af4a584fcfa5a406eb170577e6c86bb260beed61acccad3eac7b80cc225fdd2c282ad7d08271e47f9ce41ef78f3035147ea1f11b4",
          "sha256": "a2b4c9ffa77ccc10c768e9c8c9869750c87c0e9238dec776661367e565cde6a4",
          "sha1": "32809ef03ebc6aa35c9686b724c5ebb5091c0c6d",
          "md5": "4dfbabe5bd86025e4e349458cf68f9f7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.0.0-alpha13/runtime-metadata-1.0.0-alpha13.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-metadata",
        "version": "1.0.0-alpha13"
      }
    }
  ]
}
