{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-alpha13/runtime-1.0.0-alpha13.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha13.klib",
          "url": "runtime-js-1.0.0-alpha13.klib",
          "size": 546234,
          "sha512": "ef1111df55fbe3c163c232339016950a2a2167c94d6302e4c3c310828958d9634631b7a5be55bcb4aedf3f3bc36e364e0371ca307b53ca548f2713e4024d72e1",
          "sha256": "7a209a0a5d0121eed94a53337d35112dfc6985b5304c1b88b4e1414455c860f1",
          "sha1": "630cff3c93943c4c7c1699de5ee422e34c8cc38c",
          "md5": "839009f40263b51ecea3dde871d4719b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha13.klib",
          "url": "runtime-js-1.0.0-alpha13.klib",
          "size": 546234,
          "sha512": "ef1111df55fbe3c163c232339016950a2a2167c94d6302e4c3c310828958d9634631b7a5be55bcb4aedf3f3bc36e364e0371ca307b53ca548f2713e4024d72e1",
          "sha256": "7a209a0a5d0121eed94a53337d35112dfc6985b5304c1b88b4e1414455c860f1",
          "sha1": "630cff3c93943c4c7c1699de5ee422e34c8cc38c",
          "md5": "839009f40263b51ecea3dde871d4719b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.0.0-alpha13/runtime-metadata-1.0.0-alpha13.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-metadata",
        "version": "1.0.0-alpha13"
      }
    }
  ]
}
