{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta08/runtime-1.0.0-beta08.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-iosarm64-1.0.0-beta08.klib",
          "size": 853200,
          "sha512": "d89fe0e3a4aa5668b80b43f651157fc24c85255a00201a7946148316bab5880ce8ae3168c4293bccade4f8ac2cfcfce21faf319e57b178c428da46f043a7b8cd",
          "sha256": "062bb39a88dd7a13810212ccdb024748cd0340c0bf8582fb95d409c9c497f562",
          "sha1": "716d6e332bf803263039060ac1d2fcdf092c98dd",
          "md5": "98ec9d9a7e0f6df04a2a791c58a902f9"
        }
      ]
    }
  ]
}
