{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta04/runtime-1.0.0-beta04.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta04.klib",
          "url": "runtime-js-1.0.0-beta04.klib",
          "size": 579874,
          "sha512": "5b54ecf5090aabf88d1d0020d9f54f62779c63707d4601ac9739726a72ff2290dca7a62973f8c4f406e713a6996e2747d53974096ec18919ccad9315dd7ba037",
          "sha256": "fd4b5b3c648bfce22d65a7166ef0c5f4ab984dd0d9967b0a4e78eec1455ed891",
          "sha1": "7d0bf705d7f007540557e13003c788b919d20488",
          "md5": "d853d3ec4b7a89c1c875a3296aacbd0a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta04.klib",
          "url": "runtime-js-1.0.0-beta04.klib",
          "size": 579874,
          "sha512": "5b54ecf5090aabf88d1d0020d9f54f62779c63707d4601ac9739726a72ff2290dca7a62973f8c4f406e713a6996e2747d53974096ec18919ccad9315dd7ba037",
          "sha256": "fd4b5b3c648bfce22d65a7166ef0c5f4ab984dd0d9967b0a4e78eec1455ed891",
          "sha1": "7d0bf705d7f007540557e13003c788b919d20488",
          "md5": "d853d3ec4b7a89c1c875a3296aacbd0a"
        }
      ]
    }
  ]
}
