{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta02/runtime-1.0.0-beta02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta02.klib",
          "url": "runtime-js-1.0.0-beta02.klib",
          "size": 566670,
          "sha512": "b10a639a4c399041fa7f63966384aa8cc13883e604c242ded79cb770dac0a92e0ceb508c51cdda7e88c5b4b5128276a25bcf1aaa8b12efd6121839655af74c3b",
          "sha256": "267dd7a9f65d281d7b69780201555efefa34ca1da65e09995b1c44a99eb7abfc",
          "sha1": "4e1fd5aa2078575392c1784f214baafdb776bda4",
          "md5": "e28611e8e7259e8f1e981cfacdb90532"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta02.klib",
          "url": "runtime-js-1.0.0-beta02.klib",
          "size": 566670,
          "sha512": "b10a639a4c399041fa7f63966384aa8cc13883e604c242ded79cb770dac0a92e0ceb508c51cdda7e88c5b4b5128276a25bcf1aaa8b12efd6121839655af74c3b",
          "sha256": "267dd7a9f65d281d7b69780201555efefa34ca1da65e09995b1c44a99eb7abfc",
          "sha1": "4e1fd5aa2078575392c1784f214baafdb776bda4",
          "md5": "e28611e8e7259e8f1e981cfacdb90532"
        }
      ]
    }
  ]
}
