{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta02/runtime-1.0.0-beta02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta02.klib",
          "url": "runtime-js-1.0.0-beta02.klib",
          "size": 568233,
          "sha512": "b92c668183eb112cc4c49bb2514f5d990385a5aef448dddfc7b6acc984f497f5424f80c387bbecb16081454c67940457dac9e26130e166f7aa468674f7bd6f2e",
          "sha256": "14fa5502ccc587159945435ddf776bee78e82cfc985f4bd8dbf532bdd7bdfda5",
          "sha1": "6b4b26de2cf8071f1de0f1b0b59d680673bfb8f9",
          "md5": "9d6dbdad61464286917a32b4685ff870"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-beta02.klib",
          "url": "runtime-js-1.0.0-beta02.klib",
          "size": 568233,
          "sha512": "b92c668183eb112cc4c49bb2514f5d990385a5aef448dddfc7b6acc984f497f5424f80c387bbecb16081454c67940457dac9e26130e166f7aa468674f7bd6f2e",
          "sha256": "14fa5502ccc587159945435ddf776bee78e82cfc985f4bd8dbf532bdd7bdfda5",
          "sha1": "6b4b26de2cf8071f1de0f1b0b59d680673bfb8f9",
          "md5": "9d6dbdad61464286917a32b4685ff870"
        }
      ]
    }
  ]
}
