{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta08/runtime-1.0.0-beta08.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-linuxx64-1.0.0-beta08.klib",
          "size": 853200,
          "sha512": "ff2f1cd674d5acd4eb871ece4ece40c5524208cfef6e1354d983f3d775b5b16f33812bb30dd882540927b5a0324f48d701d98e983419590112b379f2fd114692",
          "sha256": "9aa9db58a069c16f8ded2730d56838efd2a8bf3127bb2ad5c5e79cd6ad9cfa9c",
          "sha1": "34a4719b2a028042de395add18bac4807cce2471",
          "md5": "2daf7e87498ff3455c4000e53e519301"
        }
      ]
    }
  ]
}
