{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-dispatch-js/1.0.0-alpha11/runtime-dispatch-js-1.0.0-alpha11.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-dispatch-js",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-dispatch-metadata-1.0.0-alpha11.jar",
          "url": "runtime-dispatch-metadata-1.0.0-alpha11.jar",
          "size": 3173,
          "sha512": "82b58cef5a16fa80a31e5ab372f180679b18ec985bf920dc952cebd72acc8274743942681fded3aab5a47675069b79e16fb85d627ae43389cf61bb52508f0f13",
          "sha256": "62a6e364f8308d0a28d4dfe8eb2740ec0498819a767d463edba41c099f354669",
          "sha1": "132d2dae30f0f8f4c22c8c006544db7b0bbd3862",
          "md5": "8b47eb935331886e356608144d1e342c"
        }
      ]
    }
  ]
}
