{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta08/runtime-1.0.0-beta08.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-iosx64-1.0.0-beta08.klib",
          "size": 853183,
          "sha512": "e33aa425a54b49a6428ced4087dc7b04d8698f88b25c68694aca4d250c8069d1b9a724c119a0349c2e65af1cc0a8aed4c2ef1cf03393dff58cea9b73dca66089",
          "sha256": "8d233b4759fdedacd0078372d4218e6c2e0f0409c2c79821aa669b6469611831",
          "sha1": "fe71a2b9561955ef7fb6fa304d8e555de92c73ad",
          "md5": "ec5c479d00e3fc0930b1d6f056190e57"
        }
      ]
    }
  ]
}
