{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-dispatch",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-dispatch-metadata-1.0.0-alpha11.jar",
          "url": "runtime-dispatch-1.0.0-alpha11.jar",
          "size": 3173,
          "sha512": "82b58cef5a16fa80a31e5ab372f180679b18ec985bf920dc952cebd72acc8274743942681fded3aab5a47675069b79e16fb85d627ae43389cf61bb52508f0f13",
          "sha256": "62a6e364f8308d0a28d4dfe8eb2740ec0498819a767d463edba41c099f354669",
          "sha1": "132d2dae30f0f8f4c22c8c006544db7b0bbd3862",
          "md5": "8b47eb935331886e356608144d1e342c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-android-debug/1.0.0-alpha11/runtime-dispatch-android-debug-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-android-debug",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-android-debug/1.0.0-alpha11/runtime-dispatch-android-debug-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-android-debug",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-android/1.0.0-alpha11/runtime-dispatch-android-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-android",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-android/1.0.0-alpha11/runtime-dispatch-android-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-android",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-desktop/1.0.0-alpha11/runtime-dispatch-desktop-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-desktop",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-dispatch-desktop/1.0.0-alpha11/runtime-dispatch-desktop-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-desktop",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-dispatch-js/1.0.0-alpha11/runtime-dispatch-js-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-js",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-dispatch-js/1.0.0-alpha11/runtime-dispatch-js-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-js",
        "version": "1.0.0-alpha11"
      }
    }
  ]
}
