{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-dispatch/1.0.0-alpha11/runtime-dispatch-1.0.0-alpha11.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-dispatch",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-dispatch-js-1.0.0-alpha11.klib",
          "url": "runtime-dispatch-js-1.0.0-alpha11.klib",
          "size": 15622,
          "sha512": "795299795f9e700be3c41352f6575d4c14da94670ff378a04e3e6ace16ee12874d7d31b1b5d57bd342ccd2a7fdf569c72dbb03d0a28a7941ca455a9a89141cc0",
          "sha256": "90bfd58a9d6e7f119426872ca3e78332bdbac8a37c8c1ec4f0e9a778cc420858",
          "sha1": "ea66fc9139d5e490cc8a594d3c226b15c71c924f",
          "md5": "c9cdd444cc70b433f0c9d4f2b2e9cbd1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-dispatch-js-1.0.0-alpha11.klib",
          "url": "runtime-dispatch-js-1.0.0-alpha11.klib",
          "size": 15622,
          "sha512": "795299795f9e700be3c41352f6575d4c14da94670ff378a04e3e6ace16ee12874d7d31b1b5d57bd342ccd2a7fdf569c72dbb03d0a28a7941ca455a9a89141cc0",
          "sha256": "90bfd58a9d6e7f119426872ca3e78332bdbac8a37c8c1ec4f0e9a778cc420858",
          "sha1": "ea66fc9139d5e490cc8a594d3c226b15c71c924f",
          "md5": "c9cdd444cc70b433f0c9d4f2b2e9cbd1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-dispatch-metadata/1.0.0-alpha11/runtime-dispatch-metadata-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-dispatch-metadata",
        "version": "1.0.0-alpha11"
      }
    }
  ]
}
