{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-alpha11/runtime-1.0.0-alpha11.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-dispatch",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha11.klib",
          "url": "runtime-js-1.0.0-alpha11.klib",
          "size": 584855,
          "sha512": "287cb6f26a19c28b1946f0fa8ec03bff0b58e820d2c803687854a709e52336a725e232038cb9ab630d8e3240532bc662d2053c951b2adf906b774085693b9da2",
          "sha256": "6b9d015c8e30a02a3f2a4e951fe5643289cf2a547049dc8e91b10d3b71e1b263",
          "sha1": "f62e69f113c91e27c062724217d1969cf5e18729",
          "md5": "8c44d9d87aa691fbd15c516ea7111806"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-dispatch",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-js-1.0.0-alpha11.klib",
          "url": "runtime-js-1.0.0-alpha11.klib",
          "size": 584855,
          "sha512": "287cb6f26a19c28b1946f0fa8ec03bff0b58e820d2c803687854a709e52336a725e232038cb9ab630d8e3240532bc662d2053c951b2adf906b774085693b9da2",
          "sha256": "6b9d015c8e30a02a3f2a4e951fe5643289cf2a547049dc8e91b10d3b71e1b263",
          "sha1": "f62e69f113c91e27c062724217d1969cf5e18729",
          "md5": "8c44d9d87aa691fbd15c516ea7111806"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.0.0-alpha11/runtime-metadata-1.0.0-alpha11.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-metadata",
        "version": "1.0.0-alpha11"
      }
    }
  ]
}
