{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.0.0-beta02/runtime-1.0.0-beta02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "macOSApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-macos-1.0.0-beta02.klib",
          "size": 540509,
          "sha512": "aaa5c36adf2e57dd2ab22da4068f2c04d55b87df9425c0e336e3f6be84d0dca4ade3ed7014d826e1b1320efae6f6e222ed373fad38ff64a55cedc9f91be09dae",
          "sha256": "355d9074b1e5d0c2e85de506518f6cce42dfa940baf9b31c938b33d77fd178b6",
          "sha1": "0a10f2809841dd60e7b43dad927e50195797f5b6",
          "md5": "dfffd49188a1825512106a3de3dd887f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../runtime-metadata/1.0.0-beta02/runtime-metadata-1.0.0-beta02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-metadata",
        "version": "1.0.0-beta02"
      }
    }
  ]
}
