{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-js/1.0.0-alpha10/runtime-js-1.0.0-alpha10.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-js",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-dispatch-metadata",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-1.0.0-alpha10.jar",
          "url": "runtime-metadata-1.0.0-alpha10.jar",
          "size": 88702,
          "sha512": "63ded3432b89ee7f2ae9aca20fec64a7984849e50102b33caf57ba176900d1f8568e33af21d526147330f4aa02c2fd7ebba3f17a70a9a21eeb07e232d7c3b141",
          "sha256": "9d44eb115f5049cf8a792018b2a5071dd512c0fd935e6925bc544b0be681d9c1",
          "sha1": "9a0552783a3332edd668d04424777e5595ef7916",
          "md5": "8920d5cd01fe96301bd1dd34628cb88e"
        }
      ]
    }
  ]
}
